<table class="form-list">
    <tr>
        <td class="scope-label">
            <button onclick="setLocation('<?php echo $this->getFlushUrl()?>')" type="button" class="scalable"><span><?php echo Mage::helper('integernet_solr')->__('Rebuild Solr Autosuggest Cache') ?></span></button>
        </td>
        <td class="scope-label">
            <?php echo Mage::helper('integernet_solr')->__('Cache for Solr autosuggest function. Contains configuration and template of autosuggest box.')?>
        </td>
    </tr>
</table>
