<?php
/**
 * integer_net Magento Module
 *
 * @category   IntegerNet
 * @package    IntegerNet_Solr
 * @copyright  Copyright (c) 2014 integer_net GmbH (http://www.integer-net.de/)
 * @author     Andreas von Studnitz <avs@integer-net.de>
 */
?>

<?php
/**
 * Autosuggest box template
 *
 * @see IntegerNet_Solr_Block_CatalogSearch_Autocomplete
 * @var $this IntegerNet_Solr_Block_CatalogSearch_Autocomplete
 */
?>

<?php if ($searchwordSuggestions = $this->getSearchwordSuggestions()): ?>

    <ul>
        <li style="display:none"></li>

    <?php foreach ($searchwordSuggestions as $index => $item): ?>
        <li title="<?php echo $this->escapeHtml($item['title']) ?>" class="<?php echo $item['row_class'] ?>">
            <span class="amount"><?php echo $item['num_of_results'] ?></span>
            <?php echo  $this->escapeHtml($item['title']) ?>
        </li>
    <?php endforeach ?>

    </ul>
    
<?php endif ?>

<?php if ($productSuggestions = $this->getProductSuggestions()): ?>

    <ul>
        <li style="display:none"></li>

    <?php foreach ($productSuggestions as $index => $item): ?>
        <li title="<?php echo $this->escapeHtml($item->name_s) ?>" class="">
            <?php echo $item->result_html_autosuggest_nonindex ?>
        </li>
    <?php endforeach ?>

    </ul>
    
<?php endif ?>