<?php
/**
 * integer_net Magento Module
 *
 * @category   IntegerNet
 * @package    IntegerNet_Solr
 * @copyright  Copyright (c) 2014 integer_net GmbH (http://www.integer-net.de/)
 * @author     Andreas von Studnitz <avs@integer-net.de>
 */
?>
<?php 
    /** @var IntegerNet_Solr_Block_Js $this */ 
?>

<?php if ($url = $this->getAjaxBaseUrl()): ?>
    <script type="text/javascript">
        document.observe("dom:loaded", function() {
            var solrResult = new SolrTabs('<?php echo $url ?>');
        });
    </script>
<?php endif ?>
