<?php
/**
 * integer_net Magento Module
 *
 * @category   IntegerNet
 * @package    IntegerNet_Solr
 * @copyright  Copyright (c) 2014 integer_net GmbH (http://www.integer-net.de/)
 * @author     Andreas von Studnitz <avs@integer-net.de>
 */
/** @var IntegerNet_Solr_Block_Result_Layer_Checkbox $this */
?>

<input type="checkbox" name="" value="" <?php if ($this->getIsChecked()): ?>checked="checked"<?php endif ?> />