<?php
/**
 * integer_net Magento Module
 *
 * @category   IntegerNet
 * @package    IntegerNet_Solr
 * @copyright  Copyright (c) 2016 integer_net GmbH (http://www.integer-net.de/)
 * @author     Andreas von Studnitz <avs@integer-net.de>
 */
?>

<?php
/* @var $this IntegerNet_Solr_Block_Result_Tabs */
?>

    <p>Tabs</p>
<?php if ($this->canShowTabs()): ?>

<div class="solr-tabs-container">

    <div class="solr-tab-products active" id="solr_tab_products">
        <a href="#" id="solr_tab_link_products"><?php echo $this->__('Products (%s)', $this->getProductResultCount()) ?></a>
    </div>

</div>



<?php endif ?>