<?php
/**
 * integer_net Magento Module
 *
 * @category   IntegerNet
 * @package    IntegerNet_Solr
 * @copyright  Copyright (c) 2016 integer_net GmbH (http://www.integer-net.de/)
 * @author     Andreas von Studnitz <avs@integer-net.de>
 */
?>

<?php
/* @var $this IntegerNet_SolrPro_Block_Tabs */
?>

<?php if ($this->canShowTabs()): ?>

<div class="solr-tabs-container">

    <div class="solr-tab" id="solr_tab_products">
        <a href="#" class="active" id="solr_tab_link_products"><?php echo $this->__('Products (%s)', $this->getProductResultCount()) ?></a>
    </div>

    <?php if ($this->getCategoryResultCount()): ?>
        <div class="solr-tab" id="solr_tab_category">
            <a href="#" id="solr_tab_link_category"><?php echo $this->__('Categories (%s)', $this->getCategoryResultCount()) ?></a>
        </div>
    <?php endif ?>

    <?php if ($this->getCmsResultCount()): ?>
    <div class="solr-tab" id="solr_tab_cms">
        <a href="#" id="solr_tab_link_cms"><?php echo $this->__('Contents (%s)', $this->getCmsResultCount()) ?></a>
    </div>
    <?php endif ?>

</div>

<?php endif ?>